on:
  - push

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checking out...'
        uses: actions/checkout@v2
      - name: 'Updating last date'
        run: date --rfc-3339=second > update
      - name: 'Updating file directories'
        run: find . -type f -not -path '*/\.*' -not \( -name 'update' -o -name 'README.md' -o -name 'files' -o -name 'cashdesk*.json' \) | sed 's|^./||' > files
      - name: 'Commit and push files'
        uses: github-actions-x/commit@v2.8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'master'
          commit-message: 'Update windev files date'
          force-add: 'true'
          files: update files
          name: 'Github Action'
          email: 'noreply@github.com'
